version: '3'
services:
  # mysql:
  #   image: mysql:8
  #   container_name: db-1
  #   ports:
  #     - "3307:3306"
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=ZekoZaki.2001
  #     - MYSQL_DATABASE=tafssir
  #   volumes:
  #     - mysql:/var/lib/mysql

  solr:
    image: solr:8.11.2
    container_name: solar
    # depends_on:
    #   - mysql
    ports:
      - "8983:8983"
    restart: always
    volumes:
      - solr:/var/lib/solr

  back-end:
    image: back-end
    # Configurations supplémentaires pour le back-end
    ports:
      - "9090:9090"
    depends_on:
      # - mysql
      - solr

  back-end2:
    image: back-end2
    # Configurations supplémentaires pour le back-end2
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url= jdbc:mysql://host.docker.internal:3307/tafssir
    depends_on:
      - back-end

  front-end:
    image: frontend
    # Configurations supplémentaires pour le front-end
    ports:
      - "8080:8080"
    depends_on:
      - back-end2

volumes:
  # mysql:
  #   external: true
  #   name: mysql
  solr:
    external: true
    name: solr
